from typing import Sized

from typing_extensions import Protocol

from .snippets_db import QueryParameters, ResultSet


class Pager(Protocol, Sized):

    @property
    def current_page(self) -> int: ...

    @property
    def is_first_page(self) -> bool: ...

    @property
    def is_last_page(self) -> bool: ...

    @property
    def must_paginate(self) -> bool: ...

    @property
    def total_rows(self) -> int: ...

    def set_query(self, query: str, params: QueryParameters = ()): ...

    def get_query(self) -> str: ...

    def set_count_query(self, query: str, params: QueryParameters = ()): ...

    def set_page_size(self, size: int): ...

    def execute(self, params: QueryParameters = (), count_params: QueryParameters = ()) -> 'Pager': ...

    def get_page(self, page: int) -> ResultSet: ...

    def first(self) -> ResultSet: ...

    def last(self) -> ResultSet: ...

    def next(self) -> ResultSet: ...

    def previous(self) -> ResultSet: ...
